name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: apt-get update && apt-get install -y clang cmake git libboost-dev libssl-dev
    - name: submodules
      run: git submodule update --init --recursive
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/clang++
    - name: build
      run: cmake --build build
    - name: test
      run: ./build/tests/tamed-test
